security:
  oauth2:
    client:
      clientId: dataset-service
      clientSecret: ${DATASET_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: datasets-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: datasets
      port: 27017

server:
  context-path: /datasets
  port: 6000
